# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Lifestation' do
  # Firebase/GoogleMaps require static frameworks - MUST be declared before any pods
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true

  config = use_native_modules!
  
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  # Use react-native-maps Google subspec so PROVIDER_GOOGLE works on iOS (includes GoogleMaps + Google-Maps-iOS-Utils)
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-maps/Google', :path => rn_maps_path
  
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Fix Firebase/Clang module resolution (FirebaseCore.h, React, GoogleMaps not found)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
    end

    # Fix RCTSwiftUI.modulemap not found when Archiving (Release-iphoneos)
    project_path = File.join(installer.sandbox.root, '..', 'Lifestation.xcodeproj')
    if File.exist?(project_path)
      require 'xcodeproj'
      project = Xcodeproj::Project.open(project_path)
      project.targets.each do |target|
        next unless target.respond_to?(:name) && target.name == 'Lifestation'
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_INCLUDE_PATHS'] ||= ['$(inherited)']
          path = '$(BUILT_PRODUCTS_DIR)'
          config.build_settings['SWIFT_INCLUDE_PATHS'] << path unless config.build_settings['SWIFT_INCLUDE_PATHS'].include?(path)
          config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        end
      end
      project.save
    end
  end
end
